name: CI

on: [push]

jobs:
  build-test:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    - name: Build app
      if: steps.cache.outputs.cache-hit != 'true'
      run: xcodebuild -project 'riskmethodsCICD.xcodeproj' -scheme 'riskmethodsCICD' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO | xcpretty
    
    - name: Run tests
      if: steps.cache.outputs.cache-hit != 'true'
      run: xcodebuild -project 'riskmethodsCICD.xcodeproj' -scheme 'riskmethodsCICD' -destination 'platform=iOS Simulator,name=iPhone 11 Pro' test | xcpretty

